import {
  StudentProfile,
  ProfessorProfile,
  AdminProfile,
  Batch,
  Course,
  AssessmentScheme,
  StudentInternalMark,
  MarkAuditLog,
  AttendanceSession,
  AuditLog,
} from "@/types";

export const MOCK_BATCHES: Batch[] = [
  {
    id: "batch-2025-27",
    name: "MSc SCB 2025–27",
    program: "MSc Systems & Computational Biology",
    department: "Department of Systems & Computational Biology",
    startYear: 2025,
    endYear: 2027,
    currentSemester: 2,
    sections: ["Section A", "Section B"],
    isActive: true,
    totalStudents: 16,
  },
  {
    id: "batch-2024-26",
    name: "MSc SCB 2024–26",
    program: "MSc Systems & Computational Biology",
    department: "Department of Systems & Computational Biology",
    startYear: 2024,
    endYear: 2026,
    currentSemester: 4,
    sections: ["Section A", "Section B"],
    isActive: true,
    totalStudents: 14,
  },
  {
    id: "batch-2023-25",
    name: "MSc SCB 2023–25",
    program: "MSc Systems & Computational Biology",
    department: "Department of Systems & Computational Biology",
    startYear: 2023,
    endYear: 2025,
    currentSemester: 4,
    sections: ["Section A"],
    isActive: false,
    totalStudents: 12,
  },
  {
    id: "batch-2026-28",
    name: "MSc SCB 2026–28",
    program: "MSc Systems & Computational Biology",
    department: "Department of Systems & Computational Biology",
    startYear: 2026,
    endYear: 2028,
    currentSemester: 1,
    sections: ["Section A", "Section B"],
    isActive: true,
    totalStudents: 18,
  },
];

export const MOCK_STUDENTS: StudentProfile[] = [
  // MSc SCB 2025-27 - Section A
  {
    id: "std-01",
    email: "ajay.k@uohyd.ac.in",
    fullName: "Ajay Kumar",
    role: "student",
    rollNumber: "25MCMS01",
    enrollmentNumber: "UOH/SLS/2025/0114",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43210",
  },
  {
    id: "std-02",
    email: "priya.singh@uohyd.ac.in",
    fullName: "Priya Singh",
    role: "student",
    rollNumber: "25MCMS02",
    enrollmentNumber: "UOH/SLS/2025/0115",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43211",
  },
  {
    id: "std-03",
    email: "rahul.sharma@uohyd.ac.in",
    fullName: "Rahul Sharma",
    role: "student",
    rollNumber: "25MCMS03",
    enrollmentNumber: "UOH/SLS/2025/0116",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43212",
  },
  {
    id: "std-04",
    email: "ananya.das@uohyd.ac.in",
    fullName: "Ananya Das",
    role: "student",
    rollNumber: "25MCMS04",
    enrollmentNumber: "UOH/SLS/2025/0117",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43213",
  },
  {
    id: "std-05",
    email: "aman.verma@uohyd.ac.in",
    fullName: "Aman Verma",
    role: "student",
    rollNumber: "25MCMS05",
    enrollmentNumber: "UOH/SLS/2025/0118",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43214",
  },
  {
    id: "std-06",
    email: "sneha.patel@uohyd.ac.in",
    fullName: "Sneha Patel",
    role: "student",
    rollNumber: "25MCMS06",
    enrollmentNumber: "UOH/SLS/2025/0119",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43215",
  },
  {
    id: "std-07",
    email: "vikram.reddy@uohyd.ac.in",
    fullName: "Vikram Reddy",
    role: "student",
    rollNumber: "25MCMS07",
    enrollmentNumber: "UOH/SLS/2025/0120",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43216",
  },
  {
    id: "std-08",
    email: "kavita.nair@uohyd.ac.in",
    fullName: "Kavita Nair",
    role: "student",
    rollNumber: "25MCMS08",
    enrollmentNumber: "UOH/SLS/2025/0121",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    semester: 2,
    phone: "+91 98765 43217",
  },

  // MSc SCB 2025-27 - Section B
  {
    id: "std-09",
    email: "rohit.gupta@uohyd.ac.in",
    fullName: "Rohit Gupta",
    role: "student",
    rollNumber: "25MCMS09",
    enrollmentNumber: "UOH/SLS/2025/0122",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "B",
    semester: 2,
    phone: "+91 98765 43218",
  },
  {
    id: "std-10",
    email: "deepika.rao@uohyd.ac.in",
    fullName: "Deepika Rao",
    role: "student",
    rollNumber: "25MCMS10",
    enrollmentNumber: "UOH/SLS/2025/0123",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "B",
    semester: 2,
    phone: "+91 98765 43219",
  },
  {
    id: "std-11",
    email: "sanjay.kumar@uohyd.ac.in",
    fullName: "Sanjay Kumar",
    role: "student",
    rollNumber: "25MCMS11",
    enrollmentNumber: "UOH/SLS/2025/0124",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "B",
    semester: 2,
    phone: "+91 98765 43220",
  },
  {
    id: "std-12",
    email: "pooja.menon@uohyd.ac.in",
    fullName: "Pooja Menon",
    role: "student",
    rollNumber: "25MCMS12",
    enrollmentNumber: "UOH/SLS/2025/0125",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "B",
    semester: 2,
    phone: "+91 98765 43221",
  },
];

export const MOCK_PROFESSOR: ProfessorProfile = {
  id: "prof-01",
  email: "dr.rao@uohyd.ac.in",
  fullName: "Prof. K. Venkatesh Rao",
  role: "professor",
  employeeCode: "EMP-UOH-882",
  department: "Department of Systems & Computational Biology",
  designation: "Professor & Head of Department",
  phone: "+91 40 2313 4500",
};

export const MOCK_PROFESSORS: ProfessorProfile[] = [
  MOCK_PROFESSOR,
  {
    id: "prof-02",
    email: "ananya.sen@uohyd.ac.in",
    fullName: "Dr. Ananya Sen",
    role: "professor",
    employeeCode: "EMP-UOH-890",
    department: "Department of Systems & Computational Biology",
    designation: "Associate Professor",
    phone: "+91 40 2313 4512",
  },
  {
    id: "prof-03",
    email: "sundaram.mk@uohyd.ac.in",
    fullName: "Dr. M. K. Sundaram",
    role: "professor",
    employeeCode: "EMP-UOH-895",
    department: "Department of Systems & Computational Biology",
    designation: "Assistant Professor",
    phone: "+91 40 2313 4518",
  },
  {
    id: "prof-04",
    email: "p.radhakrishnan@uohyd.ac.in",
    fullName: "Prof. P. Radhakrishnan",
    role: "professor",
    employeeCode: "EMP-UOH-870",
    department: "Department of Systems & Computational Biology",
    designation: "Senior Professor & Chair",
    phone: "+91 40 2313 4525",
  },
];

export const MOCK_ADMIN: AdminProfile = {
  id: "adm-01",
  email: "academic.admin@uohyd.ac.in",
  fullName: "Dr. S. R. Murthy",
  role: "admin",
  department: "Dean's Office, School of Life Sciences",
  phone: "+91 40 2313 4001",
};

export const MOCK_COURSES: Course[] = [
  {
    id: "course-scb-501",
    code: "SCB-501",
    name: "Molecular Biology & Structural Bioinformatics",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    semester: 2,
    credits: 4,
    professorId: "prof-01",
    professorName: "Prof. K. Venkatesh Rao",
    room: "LH-204",
    scheduleTime: "10:00 AM – 11:30 AM",
    scheduleDays: ["Monday", "Wednesday", "Friday"],
    timeTableSlots: [
      { id: "slot-501-1", day: "Monday", startTime: "10:00 AM", endTime: "11:30 AM", room: "LH-204", sessionType: "LECTURE" },
      { id: "slot-501-2", day: "Wednesday", startTime: "10:00 AM", endTime: "11:30 AM", room: "LH-204", sessionType: "LECTURE" },
      { id: "slot-501-3", day: "Friday", startTime: "09:30 AM", endTime: "11:30 AM", room: "Bioinformatics Lab-1", sessionType: "LAB" },
    ],
    totalStudents: 8,
    totalConductedSessions: 26,
    availableBatches: ["batch-2025-27", "batch-2024-26"],
  },
  {
    id: "course-scb-502",
    code: "SCB-502",
    name: "Computational Genomics & Sequence Algorithms",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    semester: 2,
    credits: 4,
    professorId: "prof-01",
    professorName: "Prof. K. Venkatesh Rao",
    room: "Bioinformatics Lab-1",
    scheduleTime: "11:30 AM – 01:00 PM",
    scheduleDays: ["Tuesday", "Thursday"],
    timeTableSlots: [
      { id: "slot-502-1", day: "Tuesday", startTime: "11:30 AM", endTime: "01:00 PM", room: "Bioinformatics Lab-1", sessionType: "LAB" },
      { id: "slot-502-2", day: "Thursday", startTime: "11:30 AM", endTime: "01:00 PM", room: "LH-204", sessionType: "LECTURE" },
    ],
    totalStudents: 8,
    totalConductedSessions: 24,
    availableBatches: ["batch-2025-27"],
  },
  {
    id: "course-scb-503",
    code: "SCB-503",
    name: "Statistical Machine Learning for Omics Data",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    semester: 2,
    credits: 3,
    professorId: "prof-01",
    professorName: "Prof. K. Venkatesh Rao",
    room: "LH-205",
    scheduleTime: "02:00 PM – 03:30 PM",
    scheduleDays: ["Monday", "Wednesday"],
    timeTableSlots: [
      { id: "slot-503-1", day: "Monday", startTime: "02:00 PM", endTime: "03:30 PM", room: "LH-205", sessionType: "LECTURE" },
      { id: "slot-503-2", day: "Wednesday", startTime: "02:00 PM", endTime: "03:30 PM", room: "LH-205", sessionType: "LECTURE" },
    ],
    totalStudents: 8,
    totalConductedSessions: 22,
    availableBatches: ["batch-2025-27", "batch-2024-26"],
  },
  {
    id: "course-scb-504",
    code: "SCB-504",
    name: "Python & R for Biological Big Data",
    department: "Department of Systems & Computational Biology",
    program: "MSc Systems & Computational Biology",
    semester: 2,
    credits: 3,
    professorId: "prof-01",
    professorName: "Prof. K. Venkatesh Rao",
    room: "High-Performance Computing Lab",
    scheduleTime: "03:30 PM – 05:00 PM",
    scheduleDays: ["Friday"],
    timeTableSlots: [
      { id: "slot-504-1", day: "Tuesday", startTime: "02:00 PM", endTime: "04:00 PM", room: "Computing Lab-2", sessionType: "LAB" },
      { id: "slot-504-2", day: "Thursday", startTime: "02:00 PM", endTime: "04:00 PM", room: "Computing Lab-2", sessionType: "LAB" },
    ],
    totalStudents: 8,
    totalConductedSessions: 18,
    availableBatches: ["batch-2025-27"],
  },
];

export const MOCK_ASSESSMENT_SCHEMES: AssessmentScheme[] = [
  {
    id: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    batchId: "batch-2025-27",
    section: "A",
    totalMaxMarks: 30,
    passingMarks: 12,
    components: [
      {
        id: "comp-midsem",
        name: "Mid-Sem Exam",
        shortCode: "MID",
        maxMarks: 10,
        order: 1,
      },
      {
        id: "comp-assignment",
        name: "Assignment",
        shortCode: "ASG",
        maxMarks: 5,
        order: 2,
      },
      {
        id: "comp-quiz",
        name: "Continuous Quiz",
        shortCode: "QZ",
        maxMarks: 5,
        order: 3,
      },
      {
        id: "comp-attendance",
        name: "Class Attendance",
        shortCode: "ATT",
        maxMarks: 5,
        order: 4,
        isAttendanceDerived: true,
      },
      {
        id: "comp-viva",
        name: "Viva-Voce",
        shortCode: "VIVA",
        maxMarks: 5,
        order: 5,
      },
    ],
  },
  {
    id: "scheme-scb-502-2025-a",
    courseId: "course-scb-502",
    batchId: "batch-2025-27",
    section: "A",
    totalMaxMarks: 30,
    passingMarks: 12,
    components: [
      {
        id: "comp-midsem-502",
        name: "Mid-Sem Theory",
        shortCode: "MID",
        maxMarks: 15,
        order: 1,
      },
      {
        id: "comp-assignment-502",
        name: "Programming Project",
        shortCode: "PRJ",
        maxMarks: 5,
        order: 2,
      },
      {
        id: "comp-quiz-502",
        name: "Quiz Series",
        shortCode: "QZ",
        maxMarks: 5,
        order: 3,
      },
      {
        id: "comp-attendance-502",
        name: "Lab Attendance",
        shortCode: "ATT",
        maxMarks: 5,
        order: 4,
        isAttendanceDerived: true,
      },
    ],
  },
];

export const MOCK_INTERNAL_MARKS: StudentInternalMark[] = [
  // Course SCB-501 - Batch 2025-27 - Section A
  {
    id: "mark-501-std-01",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-01",
    studentRollNumber: "25MCMS01",
    studentName: "Ajay Kumar",
    componentScores: {
      "comp-midsem": 9,
      "comp-assignment": 5,
      "comp-quiz": 4.5,
      "comp-attendance": 5,
      "comp-viva": 4.5,
    },
    totalScore: 28,
    percentage: 93.3,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-02",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-02",
    studentRollNumber: "25MCMS02",
    studentName: "Priya Singh",
    componentScores: {
      "comp-midsem": 9.5,
      "comp-assignment": 5,
      "comp-quiz": 5,
      "comp-attendance": 5,
      "comp-viva": 5,
    },
    totalScore: 29.5,
    percentage: 98.3,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-03",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-03",
    studentRollNumber: "25MCMS03",
    studentName: "Rahul Sharma",
    componentScores: {
      "comp-midsem": 8,
      "comp-assignment": 4,
      "comp-quiz": 4,
      "comp-attendance": 4,
      "comp-viva": 4,
    },
    totalScore: 24,
    percentage: 80.0,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-04",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-04",
    studentRollNumber: "25MCMS04",
    studentName: "Ananya Das",
    componentScores: {
      "comp-midsem": 8.5,
      "comp-assignment": 4.5,
      "comp-quiz": 4.5,
      "comp-attendance": 5,
      "comp-viva": 4.5,
    },
    totalScore: 27,
    percentage: 90.0,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-05",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-05",
    studentRollNumber: "25MCMS05",
    studentName: "Aman Verma",
    componentScores: {
      "comp-midsem": 4.5,
      "comp-assignment": 3,
      "comp-quiz": 2.5,
      "comp-attendance": 2,
      "comp-viva": 2.5,
    },
    totalScore: 14.5,
    percentage: 48.3,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-06",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-06",
    studentRollNumber: "25MCMS06",
    studentName: "Sneha Patel",
    componentScores: {
      "comp-midsem": 7.5,
      "comp-assignment": 4,
      "comp-quiz": 4,
      "comp-attendance": 4,
      "comp-viva": 4,
    },
    totalScore: 23.5,
    percentage: 78.3,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-07",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-07",
    studentRollNumber: "25MCMS07",
    studentName: "Vikram Reddy",
    componentScores: {
      "comp-midsem": 5,
      "comp-assignment": 3.5,
      "comp-quiz": 3,
      "comp-attendance": 2.5,
      "comp-viva": 3,
    },
    totalScore: 17,
    percentage: 56.7,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
  {
    id: "mark-501-std-08",
    schemeId: "scheme-scb-501-2025-a",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    studentId: "std-08",
    studentRollNumber: "25MCMS08",
    studentName: "Kavita Nair",
    componentScores: {
      "comp-midsem": 8,
      "comp-assignment": 4.5,
      "comp-quiz": 4,
      "comp-attendance": 5,
      "comp-viva": 4,
    },
    totalScore: 25.5,
    percentage: 85.0,
    status: "PUBLISHED",
    finalizedAt: "2026-08-16T14:30:00Z",
    finalizedBy: "Prof. K. Venkatesh Rao",
    publishedAt: "2026-08-17T09:00:00Z",
    publishedBy: "Prof. K. Venkatesh Rao",
  },
];

export const MOCK_MARK_AUDIT_LOGS: MarkAuditLog[] = [
  {
    id: "m-audit-01",
    studentId: "std-01",
    studentRollNumber: "25MCMS01",
    studentName: "Ajay Kumar",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    batchId: "batch-2025-27",
    section: "A",
    componentName: "Mid-Sem Exam",
    oldScore: 8,
    newScore: 9,
    changedBy: "Prof. K. Venkatesh Rao",
    changedByRole: "professor",
    reason: "Corrected Mid-Sem question 3 evaluation after student review.",
    timestamp: "2026-08-17T08:45:00Z",
  },
];

export const MOCK_SESSIONS: AttendanceSession[] = [
  {
    id: "sess-today-01",
    courseId: "course-scb-501",
    courseCode: "SCB-501",
    courseName: "Molecular Biology & Structural Bioinformatics",
    batchId: "batch-2025-27",
    batchName: "MSc SCB 2025–27",
    section: "A",
    professorId: "prof-01",
    professorName: "Prof. K. Venkatesh Rao",
    program: "MSc Systems & Computational Biology",
    semester: 2,
    room: "LH-204",
    date: "2026-08-17",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    sessionType: "QR",
    status: "ACTIVE",
    qrToken: "uohyd-scb501-live-token-84920",
    attendanceCode: "7X4P9",
    expiresAt: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
    createdAt: "2026-08-17T10:00:00Z",
    records: [
      {
        id: "rec-01",
        sessionId: "sess-today-01",
        studentId: "std-01",
        studentRollNumber: "25MCMS01",
        studentName: "Ajay Kumar",
        status: "PRESENT",
        markedVia: "QR",
        markedAt: "10:02 AM",
      },
      {
        id: "rec-02",
        sessionId: "sess-today-01",
        studentId: "std-02",
        studentRollNumber: "25MCMS02",
        studentName: "Priya Singh",
        status: "PRESENT",
        markedVia: "QR",
        markedAt: "10:03 AM",
      },
      {
        id: "rec-03",
        sessionId: "sess-today-01",
        studentId: "std-03",
        studentRollNumber: "25MCMS03",
        studentName: "Rahul Sharma",
        status: "PRESENT",
        markedVia: "CODE",
        markedAt: "10:05 AM",
      },
      {
        id: "rec-04",
        sessionId: "sess-today-01",
        studentId: "std-04",
        studentRollNumber: "25MCMS04",
        studentName: "Ananya Das",
        status: "PRESENT",
        markedVia: "QR",
        markedAt: "10:06 AM",
      },
      {
        id: "rec-05",
        sessionId: "sess-today-01",
        studentId: "std-05",
        studentRollNumber: "25MCMS05",
        studentName: "Aman Verma",
        status: "ABSENT",
        markedVia: "MANUAL",
        markedAt: "10:15 AM",
      },
      {
        id: "rec-06",
        sessionId: "sess-today-01",
        studentId: "std-06",
        studentRollNumber: "25MCMS06",
        studentName: "Sneha Patel",
        status: "PRESENT",
        markedVia: "QR",
        markedAt: "10:08 AM",
      },
      {
        id: "rec-07",
        sessionId: "sess-today-01",
        studentId: "std-07",
        studentRollNumber: "25MCMS07",
        studentName: "Vikram Reddy",
        status: "ABSENT",
        markedVia: "MANUAL",
        markedAt: "10:15 AM",
      },
      {
        id: "rec-08",
        sessionId: "sess-today-01",
        studentId: "std-08",
        studentRollNumber: "25MCMS08",
        studentName: "Kavita Nair",
        status: "LATE",
        markedVia: "MANUAL",
        markedAt: "10:18 AM",
        remarks: "Arrived after 15m window; verified by instructor",
      },
    ],
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "audit-01",
    sessionId: "sess-today-01",
    courseName: "Molecular Biology & Structural Bioinformatics",
    actorId: "prof-01",
    actorName: "Prof. K. Venkatesh Rao",
    actorRole: "professor",
    action: "STATUS_OVERRIDE",
    targetStudentName: "Kavita Nair",
    targetStudentRoll: "25MCMS08",
    oldValue: "ABSENT",
    newValue: "LATE",
    reason: "Student submitted medical pass from University Health Center.",
    timestamp: "2026-08-17T10:18:24Z",
  },
  {
    id: "audit-02",
    sessionId: "sess-past-02",
    courseName: "Computational Genomics & Sequence Algorithms",
    actorId: "adm-01",
    actorName: "Dr. S. R. Murthy",
    actorRole: "admin",
    action: "SESSION_REOPEN",
    reason: "Institutional review of lab attendance dispute for Session #24.",
    timestamp: "2026-08-15T16:00:12Z",
  },
];
